name: Build and Run C Program

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        gcc-version: [9, 10, 11]  # Define GCC versions to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile C program
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp gcc:${{ matrix.gcc-version }} gcc -o hello hello.c
        # Compiling the C program using the specified GCC version

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binaries
          path: ./hello
        # Upload the compiled binary for later use or download

      - name: Run C program
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp gcc:${{ matrix.gcc-version }} ./hello
        # Running the compiled C program
