name: Build and Run C Program

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile and run C program
        uses: docker://gcc:latest
        with:
          entrypoint: "/bin/bash"
          args: "-c 'gcc -o hello hello.c && ./hello'"
