name: Build and Run C Program

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        gcc-version: [9, 10, 11]  # Testing with GCC versions 9, 10, and 11

    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}  # Referencing a secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile C program
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp gcc:${{ matrix.gcc-version }} gcc -o hello hello.c

      - name: Run C program
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp gcc:${{ matrix.gcc-version }} ./hello

      - name: Run unit tests
        run: ./run-tests.sh  # Example step to run tests if applicable
