name: Hello Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
    - name: Run a PowerShell script
      shell: pwsh
      run: echo "Hello Actions!"
